
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 10 20:21:03 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 5;
  public static final int GRT = 28;
  public static final int TERNARY = 44;
  public static final int CASE = 41;
  public static final int LPAREN = 13;
  public static final int SEMI = 6;
  public static final int CONTINUE = 17;
  public static final int FOR = 42;
  public static final int MINUS = 33;
  public static final int CHARACTER = 48;
  public static final int RPAREN = 14;
  public static final int AND = 25;
  public static final int OR = 24;
  public static final int BOOL = 47;
  public static final int COMMA = 8;
  public static final int INC = 21;
  public static final int DIV = 35;
  public static final int PLUS = 32;
  public static final int ASSIGN = 7;
  public static final int IF = 15;
  public static final int GRTEQL = 29;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int MUL = 34;
  public static final int NUMBER = 46;
  public static final int MOD = 36;
  public static final int IDENT = 45;
  public static final int BREAK = 16;
  public static final int VOID = 12;
  public static final int SWITCH = 40;
  public static final int LBRACK = 9;
  public static final int COLON = 43;
  public static final int LBRACE = 3;
  public static final int ELSE = 23;
  public static final int ENUM = 11;
  public static final int READ = 19;
  public static final int RBRACK = 10;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int LWREQL = 31;
  public static final int ISEQL = 26;
  public static final int NOTEQL = 27;
  public static final int DEC = 22;
  public static final int LWR = 30;
  public static final int LENGTH = 39;
  public static final int PRINT = 20;
}

